name: playbite
description: TikTok for Games

publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  webview_flutter: ^4.4.4
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    - assets/logo/